= My NixOS configurations

[NOTE]
====
This is latest config. All the deprecated packages / variables are fixed.
====

== Makefile

I've wrote the `Makefile` to use the `./configuration.nix` file as the main
config file. If you don't want to use `make` or it's not available on your
system, simply add `--include nixos-config=./configuration.nix` flag into your
`nixos-rebuild` command.

Available make commands are pretty much the same as `nixos-rebuild`:

* `make test`
* `make build`
* `make boot`
* `make switch`

There is also some extra commands:

. `make clean` -- Which will run `nix-collect-carbage -d` command first, then
  the `nixos-rebuild switch` afterwards.
. `make upgrade` -- Which will run `nixos-rebuild boot --upgrade` to upgrade
  the channels and the whole system.
. `make readme` -- generates html file from this (README) file using
  `asciidoctor` to be able to read this file with a better look in a browser.

== TODO

* [ ] Add more about Nix language
* [ ] Server / NixOps deployment
* [ ] Different hardware and partition schema

== Nix language syntax short overview

NixOS is a Linux distrbution that uses the Nix Programming language at its best
to have a declaretive approach for deploying the system.

A very quick look at the nix's syntax:

=== Data types
[source,nix]
----
# strings
"a"

# numbers (aka integers)
26

# booleans
true / false

# paths
./hardware/nvidia.nix

# arrays (aka lists)
[1 2 3];
[ # more arrays
    "a"
    "b"
    "c"
];

# objects (aka sets)
{
    user = "hos";
    uuid = 1000;
};
----

=== Variables
[source,nix]
----
# variable
let
    var = "some string";
in {
    use.like.this.${var} = [
        ./one
        ./two
    ];
};
----

=== Run code
[source,console]
----
$ nix-instantiate --eval <file>.nix
----

=== Access values

.accessing sets
[source,nix]
----
{
    user = "hos";
    uuid = 1000;
}.user; # "hos"
----

.`with` keyword
[source,nix]
----
let
    set = {
        x = "foo";
        y = "bar";
    };
in with set;
    x + y # "foobar"
----

.create functions
[source,nix]
----
let
    square = x; x * y;
in
    square 16; # 256
----

[source,nix]
----
let
    test = {a, b}: 2 * (a + b);
in
    test { a = 1; b = 2 }
----

.`...` unlimited arguments
[source,nix]
----
let
    test = {a, ...}@args: 2 * (a + args.b);
in
    test { a = 1; b = 2 }
----

== TODO

* [ ] neovim config
* [ ] add desktop/window managers
* [ ] add power-saving and performance mode profiles
* [ ] add `disko` config

== Links

* https://nixos.org/download[download NixOS]
* https://nixos.org/manual/nixos/stable[NixOS Manual]
* https://search.nixos.org/packages[Search packages]
* https://github.com/nix-community/disko/tree/master/example[disko examples]
* https://nix.dev/manual/nix/2.22/introduction[Nix Reference Manual]
* https://nixos.org/guides/nix-pills/06-our-first-derivation[Nix Pills]
* https://home-manager-options.extranix.com/[Home Manager Option Search]
* https://zero-to-nix.com/[Zero to Nix]
* https://edolstra.github.io/pubs/phd-thesis.pdf[PhD Thesis]
